### ISSUE TITLE
运行node example.js 提示找不到bl

### ISSUE THREAD

**Issue by nixionglin** [Yuliang-Lee/gitlab-webhook-handler#1]
E:\code\github\gitlab-webhook-handler2>node example.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'bl'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\code\github\gitlab-webhook-handler2\gitlab-webhook
-handler.js:7:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by Yuliang-Lee** [comment]
先`npm install`安装依赖
